web:
  build: .
  command: 'node server.js'
  environment:
    PORT: '3000'
    REDIS_URL: 'redis://redis:6379'
    DATABASE_URL: 'postgres://postgres:6212'
  ports:
    - '3000:3000'
  links:
    - herokuRedis
    - herokuPostgresql
worker:
  build: .
  command: 'node server.js'
  environment:
    REDIS_URL: 'redis://redis:6379'
    DATABASE_URL: 'postgres://postgres:6212'
  links:
    - herokuRedis
    - herokuPostgresql
herokuRedis:
  image: redis
herokuPostgresql:
  image: postgres
